app/mod_authentication/controllers.py
# Import flask dependencies
from flask import Blueprint, request, render_template, session, url_for, flash

# Import the database object from the main app module
from app import db, db_usuarios

# Import module forms
from app import app

# Import module models (i.e. User)
	#from app.mod_authentication.models import User

# Define the blueprint: 'auth', set its url prefix: app.url/auth
from app.mod_state.controllers import mod_state, state_index

mod_authentication = Blueprint('authentication', __name__, url_prefix='/user')
mod_state = Blueprint('state', __name__, url_prefix='/state')

# Set the route and accepted methods
@mod_authentication.route('/')
@mod_authentication.route('/signin/')
def signin(error):
	if error == None:
		return render_template("authentication/signin.html")
	return render_template("authentication/signin.html", error=error)

@mod_authentication.route('/login', methods=['GET', 'POST'])
def login():
	error = None

	user = db_usuarios
	existing_user = user.find_one({'email' : request.form['email']})

	if existing_user:
		if (request.form['password'] == existing_user['password']):
			session['id'] 		= existing_user['id']
			session['name'] 	= existing_user['nombre']
			session['email'] 	= existing_user['email']
			session['password'] = existing_user['password']
			session['ruta_foto_perfil'] = existing_user['ruta_foto_perfil']
			return state_index()
		error = 'Datos invalidos'
	error = 'Datos invalidos'
	
	return signin(error)

@mod_authentication.route('/register', methods=['GET', 'POST'])
def register():

	return render_template("authentication/register.html")

@mod_authentication.route('/new_register', methods=['GET', 'POST'])
def new_register():
#Para registrar un nuevo usuario en la BD
	error = None

	if request.method == 'POST':
		user = db_usuarios
		existing_user = user.find_one({'email' : request.form['email']})

		if existing_user is None:
			#hashpass = bcrypt.haspw(request.form['password'].encode('utf-8'), bcrypt.genSalt())
			hashpass = request.form['password']

			new_user = {
				"nombre" : request.form['name'],
				"email" : request.form['email'],
				"password" : hashpass,
				"ruta_foto_perfil" : "../../static/images/new.png"
			}

			user.insert_one(new_user)
			session['id'] 		= 100
			session['name'] 	= request.form['name']
			session['email'] 	= request.form['email']
			session['password'] = hashpass
			session['ruta_foto_perfil'] = "../../static/images/new.png"
			return state_index()

		error = 'El correo ya existe!'

	return render_template("authentication/register.html", error=error)

@mod_authentication.route('/logout/', methods=['GET', 'POST'])
@mod_state.route('/logout/')
@app.route('/logout/')
def logout():

    session.pop('name', None)
    session.pop('email', None)
    session.pop('email', None)

    return render_template("authentication/signin.html")

app/templates/authentication/amigos.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<div class="panel-group" id="accordion">

  <div class="panel panel-default">  	
  	<div class="panel-heading">
  		<h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse1">Bruce Wayne</a></h4>
  	</div>
  	<div id="collapse1" class="panel-collapse collapse">
  		<div class="panel-body scroll-bar-style1">
      		Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      		sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
      		minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      		commodo consequat.
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  		</div>
  		<div class="panel-footer">
        <input type="text" class="chat_area" placeholder="Escribe un mensaje..">
        <button class="btn btn-info bnt-xs">Enviar</button>
      </div>
  	</div>
  </div>

  <div class="panel panel-default">  	
  	<div class="panel-heading">
  		<h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse2">Kal El</a></h4>
  	</div>
  	<div id="collapse2" class="panel-collapse collapse">
  		<div class="panel-body">
      		Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      		sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
      		minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      		commodo consequat.
  		</div>
  		<div class="panel-footer">
      <input type="text" class="chat_area" placeholder="Escribe un mensaje..">
        <button class="btn btn-info bnt-xs">Enviar</button>  
      </div>
  	</div>
  </div>

  <div class="panel panel-default">  	
  	<div class="panel-heading">
  		<h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse3">Barry Allen</a></h4>
  	</div>
  	<div id="collapse3" class="panel-collapse collapse">
  		<div class="panel-body">
      		Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      		sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
      		minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      		commodo consequat.
  		</div>
  		<div class="panel-footer">
      <input type="text" class="chat_area" placeholder="Escribe un mensaje..">
        <button class="btn btn-info bnt-xs">Enviar</button>  
      </div>
  	</div>
  </div>

  <div class="panel panel-default">  	
  	<div class="panel-heading">
  		<h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse4">Diana Prince</a></h4>
  	</div>
  	<div id="collapse4" class="panel-collapse collapse">
  		<div class="panel-body">
      		Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      		sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
      		minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      		commodo consequat.
  		</div>
  		<div class="panel-footer">
        <input type="text" class="chat_area" placeholder="Escribe un mensaje..">
        <button class="btn btn-info bnt-xs">Enviar</button>
      </div>
  	</div>
  </div>

   <div class="panel panel-default">  	
  	<div class="panel-heading">
  		<h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse5">Arthur Curry</a></h4>
  	</div>
  	<div id="collapse5" class="panel-collapse collapse">
  		<div class="panel-body">
      		Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      		sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
      		minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      		commodo consequat.
  		</div>
  		<div class="panel-footer">
      <input type="text" class="chat_area" placeholder="Escribe un mensaje..">
        <button class="btn btn-info bnt-xs">Enviar</button>  
      </div>
  	</div>
  </div>

   <div class="panel panel-default">  	
  	<div class="panel-heading">
  		<h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse6">Hal Jordan</a></h4>
  	</div>
  	<div id="collapse6" class="panel-collapse collapse">
  		<div class="panel-body">
      		Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      		sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
      		minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      		commodo consequat.
  		</div>
  		<div class="panel-footer">
      <input type="text" class="chat_area" placeholder="Escribe un mensaje..">
        <button class="btn btn-info bnt-xs">Enviar</button>  
      </div>
  	</div>
  </div>

  <div class="panel panel-default">  	
  	<div class="panel-heading">
  		<h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse7">J'onn J'onzz</a></h4>
  	</div>
  	<div id="collapse7" class="panel-collapse collapse">
  		<div class="panel-body">
      		Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      		sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
      		minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      		commodo consequat.
  		</div>
  		<div class="panel-footer">
      <input type="text" class="chat_area" placeholder="Escribe un mensaje..">
        <button class="btn btn-info bnt-xs">Enviar</button>  
      </div>
  	</div>
  </div>

   <div class="panel panel-default">  	
  	<div class="panel-heading">
  		<h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse8">Dick Grayson</a></h4>
  	</div>
  	<div id="collapse8" class="panel-collapse collapse">
  		<div class="panel-body">
      		Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      		sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
      		minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      		commodo consequat.
  		</div>
  		<div class="panel-footer">
      <input type="text" class="chat_area" placeholder="Escribe un mensaje..">
        <button class="btn btn-info bnt-xs">Enviar</button>  
      </div>
  	</div>
  </div>
  
</div>

</body>
</html>

app/templates/authentication/index.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<!--CSS-->
	<link rel="stylesheet" type="text/css" href="../static/vendor/css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="../static/css/style_navegation_bar.css">
	<link rel="stylesheet" type="text/css" href="../static/css/style_base_container.css">
	<link rel="stylesheet" type="text/css" href="../static/css/style_lateral_chat.css">
	<!--********************************************************************-->
	<!--JS SRC-->
	<script type="text/javascript" src="../static/vendor/js/jquery.js"></script>
	<script type="text/javascript" src="../static/vendor/js/bootstrap.js"></script>
	<!--********************************************************************-->

</head>
<body>

<!--BARRA DE NAVEGACION-->

  <div class="navegation_bar">
    <div class="row row-list">
      <div class=" col-xs-12 col-sm-12 col-md-12">
          <div>
            <ul class="navbar-right">
          <li><a href="#"><p> Muro </p><span class="glyphicon glyphicon-list-alt"></span></a></li>
          <li><a href="#"><p> Perfil </p><span class="glyphicon glyphicon-home"></span></a></li>
          <li><a href="#"><p> Amigos </p><span class="glyphicon glyphicon-user"></span></a></li>
          <li><a href="#"><p> Mensajes </p><span class="glyphicon glyphicon-comment"></span></a></li>
          <li><a href="#"><p> Notificaciones </p><span class="glyphicon glyphicon-globe"></span></a></li>
          <li class="close-session"><a href="#"><p> Cerrar sesión </p><span class="glyphicon glyphicon-log-out"></span></a></li>
            </ul>
          </div>
      </div>
    </div>
  </div>

 <!--********************************************************************-->

 <div class="container-fluid">
 	<div class="row">

 		<div class="col-xs-12 col-sm-7 col-md-8">
 			<!--DENTRO DE EL DENTRO DE BASE_CONTAINER AGREGAR CODIGO DE LOS OTROS MODULOS-->
 			<!-- SI SE QUIERE USAR IFRAME <iframe src="" id="base_container"></iframe>-->
	 			<div id="base_container" class="scroll-bar-style" style="text-align:center" style="width:200px;border:1px dotted black;text-align:center">
					<div class="col-md-1"></div>
					<div class="col-md-5">
						<img src = "../static/img/anne.jpg" width="450" height="450" ></img>
					</div>
					<div class="perfil_container" class="col-md-5" width="300" height="300">
						<form style="background-color:#cccccc" text-align = center>
							<br />
				 				<b> Nombre : </b>
				  			<br />
				 					<p class="p1">Karen</p>

				 				<b> Apellido : </b> <br />
				 					<p class="p1">Gonzalez</p>

				 				<b> Edad : </b> <br />
				 					<p class="p1">29</p>

				 				<b> Color favorito : </b> <br />
				 					<p class="p1">Rosado</p>

				 				<b> Mostrar a : </b>
				 				<br />
									<select name="mostrar">
				 					   <option value="1">Mis Amigos</option>
				 					   <option value="2">Todos</option>
				 					</select> <br /><br />

								<button class="button button2">Editar</button>

					</form>
				</div>
					<div class="col-md-1"></div>
		</div>

 		</div>

		<div class=" hidden-xs col-sm-5 col-md-4">

			<!--BARRA CHAT-->

			<div class="right_chat_module ">

				<div class="container_search">
					<img src="../static/img/search.png" width="30px;" id="search_img">
					<input type="text" name="buscador_amigos" id="buscador_amigos" placeholder=" Buscar amigo ">
					<button class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-send"></span></button>
				</div>

				<div class="container_lista_amigos scroll-bar-style">

					<!--SCRIPT TEMPORAL SOLO PARA EL PROTOTIPO FASE1-->
					<script type="text/javascript">
						$(".container_lista_amigos").load("amigos.html");
					</script>
					<!--********************************************-->

				</div>

			</div>

		</div>

 	</div>
 </div>


<!--JS SRC-->
<script type="text/javascript" src="../static/js/navegation_bar.js"></script>
<!--********************************************************************-->

</body>
</html>

app/templates/authentication/register.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Red ParaATI</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='vendor/bootstrap-3.3.7/bootstrap.min.css')}}" >
  <script src="{{ url_for('static',filename='vendor/js/jquery-3.2.1.min.js')}}"></script>
  <script src="{{ url_for('static',filename='vendor/bootstrap-3.3.7/bootstrap.min.js')}}"></script>
  <!--

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  -->
</head>
<body style = "background-color: white;">

<div class="container"> 
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="../../static/img/ucv1.jpg" alt="ucv1" style="width: auto; height: 225px; max-height: 225px;">
      </div>

      <div class="item">
        <img src="../../static/img/ucv2.jpg" alt="ucv2" style="width: auto; height: 225px; max-height: 225px;">
      </div>
    
      <div class="item">
        <img src="../../static/img/ucv3.jpg" alt="ucv3" style="width: auto; height: 225px; max-height: 225px;">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>


<div class="container">
  <h1 style ="text-align: center; color: #0000ff;">Red ParATI</h1></br>
  <h2 style ="text-align: center; color: #0000ff;">Registrate!</h2></br>

  {% if error %}
  <span class="label label-danger">Error: {{ error }}</span>
  {% endif %}


   <div>
  <a href='#'> <img class =img-responsive src="../../static/img/bface.png" class="img-rounded" alt="facebookbutton"> </a>
  </div></br>

  <div>
  <a href='#'><img class =img-responsive src="../../static/img/btwitter.png" class="img-rounded" alt="twitterbutton"> </a>
  </div>



  <form action="{{ url_for('authentication.new_register') }}" method="post">
  
      <div class = "form-group">
            <label for="nombre" style = "color: #0000ff;">Nombre: </label>
            <input type="text" class="form-control" id="name" name="name" placeholder=" ESCRIBIR NOMBRE">

      </div>
    	
      <div class = "form-group">
            <label for="correo" style = "color: #0000ff;">Correo: </label>
            <input type="text" class="form-control" id="usr" name="email" placeholder=" ESCRIBIR CORREO">

      </div>

      <div class = "form-group">

            <label for="pass" style = "color: #0000ff;"> Contraseña: </label>
            <input type="password" class="form-control" id="pass" name="password" placeholder=" ESCRIBIR CONTRASEÑA">

      </div>
    	
    	<div class = "form-group">

            <label for="conpass" style = "color: #0000ff;"> Confirmar contraseña: </label>
            <input type="password" class="form-control" id="conpass" name="password2" placeholder=" CONFIRMAR CONTRASEÑA">

      </div>

     <button type="submit" class="btn btn-info">Registrar</button> </br></br>
  </form>

 



</body>
</html>

app/templates/authentication/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Red ParaATI</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='vendor/bootstrap-3.3.7/bootstrap.min.css')}}" >
  <script src="{{ url_for('static',filename='vendor/js/jquery-3.2.1.min.js')}}"></script>
  <script src="{{ url_for('static',filename='vendor/bootstrap-3.3.7/bootstrap.min.js')}}"></script>
  <!--

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  -->

</head>
<body style = "background-color: white;">

<div class="container"> 
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="../../static/img/ucv1.jpg" alt="ucv1" style="width: auto; height: 225px; max-height: 225px;">
      </div>

      <div class="item">
        <img src="../../static/img/ucv2.jpg" alt="ucv2" style="width: auto; height: 225px; max-height: 225px;">
      </div>
    
      <div class="item">
        <img src="../../static/img/ucv3.jpg" alt="ucv3" style="width: auto; height: 225px; max-height: 225px;">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>


<div class="container">
  <h1 style ="text-align: center; color: #0000ff;">Red ParATI</h1>

  {% if error %}
  <span class="label label-danger">Error: {{ error }}</span>
  {% endif %}

  <form action = "{{ url_for('authentication.login') }}" method="post">
    <div class = "form-group">
        <label for="correo" style = "color: #0000ff;">Correo: </label>
        <input type="text" class="form-control" id="usr" name="email" placeholder=" ESCRIBIR CORREO">

    </div>

    <div class = "form-group">

        <label for="pass" style = "color: #0000ff;"> Contraseña: </label>
        <input type="password" class="form-control" id="pass" name="password" placeholder=" ESCRIBIR CONTRASEÑA">

    </div>
    <button type="submit" class="btn btn-info">Ingresar</button></br>
  </form>

  

  
  <a href="#">Olvidé mi contraseña</a><br>

  <div>
  <a href="{{ url_for('authentication.register') }}">Regístrate </a><br>
  <div/>

  <div>
  <a href='#'> <img class =img-responsive src="../../static/img/bface.png" class="img-rounded" alt="facebookbutton"> </a>
  </div>

  <div>
  <a href='#'><img class =img-responsive src="../../static/img/btwitter.png" class="img-rounded" alt="twitterbutton"> </a>
  </div>

</div>

</body>
</html>

app/templates/authentication/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Red ParaATI</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body style = "background-color: white;">

<div class="container"> 
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="../static/img/ucv1.jpg" alt="ucv1" style="width: auto; height: 225px; max-height: 225px;">
      </div>

      <div class="item">
        <img src="../static/img/ucv2.jpg" alt="ucv2" style="width: auto; height: 225px; max-height: 225px;">
      </div>
    
      <div class="item">
        <img src="../static/img/ucv3.jpg" alt="ucv3" style="width: auto; height: 225px; max-height: 225px;">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>


<div class="container">
  <h1 style ="text-align: center; color: #0000ff;">Red ParATI</h1>


  <form>
    <div class = "form-group">
        <label for="correo" style = "color: #0000ff;">Correo: </label>
        <input type="text" class="form-control" id="usr" placeholder=" ESCRIBIR CORREO">

    </div>

    <div class = "form-group">

        <label for="pass" style = "color: #0000ff;"> Contraseña: </label>
        <input type="password" class="form-control" id="pass" placeholder=" ESCRIBIR CONTRASEÑA">

    </div>
  </form>

  <button type="button" class="btn btn-info">Ingresar</button></br>

  
  <a href="#">Olvidé mi contraseña</a><br>

  <div>
  <a href="register.html">Regístrate </a><br>
  <div/>

  <div>
  <a href='#'> <img class =img-responsive src="../static/img/bface.png" class="img-rounded" alt="facebookbutton"> </a>
  </div>

  <div>
  <a href='#'><img class =img-responsive src="../static/img/btwitter.png" class="img-rounded" alt="twitterbutton"> </a>
  </div>

</div>

</body>
</html>